---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployer-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: concourse
roleRef:
  kind: Role
  name: deployer
  apiGroup: rbac.authorization.k8s.io