---
resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.9"

resources:
- name: kubernetes-deployment
  type: kubernetes
  source:
    server: ((aws_k8s_host))
    token: ((k8s_token))
    certificate_authority: ((k8s-cert))

- name: fun-with-concourse
  type: git
  source:
    uri: https://github.com/zariye/fun-with-concourse.git
    branch: master

- name: fun-image
  type: docker-image
  source:
    repository: ((ecr_repo))
    tag: latest
    aws_access_key_id: ((aws_access_key_id))
    aws_secret_access_key: ((aws_secret_access_key))

jobs:
- name: publish
  plan:
  - get: fun-with-concourse
  - put: fun-image
    params: {build: fun-with-concourse/app}

- name: smoke-test
  plan:
  - get: fun-image
    passed: [publish]
  - get: fun-with-concourse
    passed: [publish]
  - task: say-hello
    image: fun-image
    file: fun-with-concourse/smoke.yml

- name: deploy
  plan:
  - get: fun-image
    passed: [smoke-test]
  - put: kubernetes-deployment
    params:
      kubectl: run deploy-image1 --image=((ecr_repo)):latest --port=3000
