---
resources:
- name: fun-with-concourse
  type: git
  source:
    uri: https://github.com/zariye/fun-with-concourse.git
    branch: master
- name: fun-image
  type: docker-image
  source:
    repository: ((ecr_repo))
    tag: latest
    aws_access_key_id: ((aws_access_key_id))
    aws_secret_access_key: ((aws_secret_access_key))

jobs:
- name: smoke
  plan:
  - get: fun-with-concourse
  - put: fun-image
    params: {build: fun-with-concours/app}
  - task: say-hello
    file: fun-with-concourse/smoke.yml
